# Generated by Django 4.1.5 on 2023-01-27 10:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_msisdn_alter_client_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, validators=[django.core.validators.MinValueValidator(limit_value=models.DateTimeField(db_index=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 1, 27, 10, 34, 31, 897766), message='Mailing start cannot be in the past')], verbose_name='Start of mailing'), message='Mailing finish cannot be earlier than mailing start')], verbose_name='Finish of mailing'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 1, 27, 10, 34, 31, 897766), message='Mailing start cannot be in the past')], verbose_name='Start of mailing'),
        ),
    ]
